#!/bin/bash
# see: http://www.commandlinefu.com/commands/view/6051/get-all-shellcode-on-binary-file-from-objdump

shellcode=$(objdump -d $1 | \
    grep '[0-9a-f]:'| grep -v 'file' | \
    cut -f2 -d: | cut -f1-6 -d' ' | \
    tr -s ' ' | tr '\t' ' ' | \
    sed 's/ $//g' | sed 's/ /\\x/g' | \
    paste -d '' -s)

# shellcode in c-style
# count bytes
length=$(echo -ne $shellcode | wc -c)
echo "// shellcode length: $length"

count=0
printf "\n#include <stdio.h>\n\n"
printf "unsigned char s[] =\n\""
for byte in $(echo $shellcode | sed 's/\\x/ /g'); do
    (( count++ ))
    printf "\\"
    printf "x$byte"

    if [ $(( $count % 16 )) -eq 0 ]; then
        printf "\"\n\""
    fi
done
printf "\";\n\n"
echo "void main() {"
echo "    printf(\"shellcode length:   %d\\n\", sizeof(s)-1);"
echo "    ((int(*)())s)();"
echo "}"

# test for null bytes
num_null=$(echo $shellcode | grep '\\x00' | wc -c)
if [ $num_null -gt 0 ]; then
    echo "// null byte(s) present!"
fi

